### ISSUE TITLE
Conda env not activated

### ISSUE THREAD

**Issue by defeo** [jupyterhub/repo2docker#411]
I am a bit confused by the way `environment.yml` works.

I tried to install R and SageMath from conda-forge, with

```yml
name: sage-r-environment
channels:
  - conda-forge
dependencies:
  - python=2.7
  - sage
  - r-essentials
```

but when I launch the Jupyter server, neither R nor SageMath notebooks are available. SageMath also does not start from a terminal (it complains about some env variables not being set).

It seems that the reason is that the conda environment is not activated prior to launching the Jupyter server. The fix for me was to add a `start` file:

```bash
#!/bin/bash

source /srv/conda/bin/activate kernel
exec "$@"
```

Also, the fact that the environment is named `kernel` instead of `sage-r-environment` is surprising.

Demo repo is here: https://github.com/defeo/sage-r

Is this a bug, or am I doing something wrong?
